<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Facility Usage Report</title>
</head>
<body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6; padding: 20px;">
    
    <div style="border-bottom: 2px solid #3b82f6; margin-bottom: 20px; padding-bottom: 10px;">
        <h1 style="margin: 0; font-size: 24px;">Facility Usage Report</h1>
        <p style="margin: 5px 0 0 0; color: #666;">Date Range: {{ $reportData['date_from'] }} to {{ $reportData['date_to'] }}</p>
    </div>
    
    <table style="width: 100%; border-collapse: collapse; margin-bottom: 30px;">
        <thead>
            <tr style="background-color: #f3f4f6;">
                <th style="padding: 10px; border: 1px solid #ddd; text-align: left;">Facility Name</th>
                <th style="padding: 10px; border: 1px solid #ddd; text-align: left;">Total Bookings</th>
            </tr>
        </thead>
        <tbody>
            @foreach($reportData['booking_frequency'] as $row)
            <tr>
                <td style="padding: 10px; border: 1px solid #ddd;">{{ $row['facility_name'] }}</td>
                <td style="padding: 10px; border: 1px solid #ddd;">{{ $row['count'] }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div style="margin-top: 20px; padding: 15px; background-color: #f9fafb; border-radius: 8px;">
        <div style="display: block; margin-bottom: 10px;">
            <strong>Cancellation Rate:</strong> {{ number_format($reportData['cancellation_rate'] * 100, 1) }}%
        </div>
        <div style="display: block;">
            <strong>Avg. Approval Turnaround:</strong> {{ $reportData['approval_turnaround_hours'] }} hours
        </div>
    </div>

    <div style="margin-top: 50px; font-size: 12px; color: #999; text-align: center;">
        Generated by Facility Management System • {{ now()->format('Y-m-d H:i') }}
    </div>
</body>
</html>